[workspace]
authors = ["Bing Li <bing.li@ess.eu>"]
channels = ["conda-forge"]
name = "align_crystal"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mcstas = ">=3.9.1,<4"
mcstasscript = ">=0.0.94,<0.0.95"
scipp = ">=25.12.0,<26"
pytest = ">=9.1.1,<10"
scippneutron = ">=26.9.1,<27"
matplotlib = ">=3.11.2,<4"

[pypi-dependencies]
align_crystal = { path = ".", editable = true }
mcstastox = { git = "https://github.com/mads-bertelsen-agentic/McStasToX", rev = "entry_choice" }
