[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "align_crystal"
version = "0.1.0"
description = "align_crystal"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Bing Li", email = "bing.li@ess.eu" }]

[tool.hatch.build.targets.wheel]
packages = ["src/align_crystal"]

[tool.pytest.ini_options]
testpaths = ["tests"]
